from typing import Protocol

import numpy as np


class ExperimentTracker(Protocol):
    def begin_run(self, run_name: str, params: dict) -> None: ...
    def log_metrics(self, metrics: dict, step: int) -> None: ...
    def log_confusion_matrix(self, cm: np.ndarray, class_names: list[str], step: int) -> None: ...
    def end_run(self) -> None: ...
